package org.bpmnwithactiviti.chapter12.rules

import org.bpmnwithactiviti.chapter12.model.LoanApplicant;
import org.bpmnwithactiviti.chapter12.model.LoanApplication;

rule "CreditCheckRule"
    
	when
		la: LoanApplicant(income > (2 * loanAmount))
	then
		la.setCheckCreditOk(true);

end

rule "LoanApplicationEvaluationRule_1"
    
	when
		la: LoanApplication((applicant.isCheckCreditOk == true) && (applicant.getLoanAmount < 100000))
	then
		la.setStatus("approved");

end

rule "LoanApplicationEvaluationRule_2"
    
	when
		la: LoanApplication((applicant.isCheckCreditOk == true) && (applicant.getLoanAmount >= 100000))
	then
		la.setStatus("needs manager approval");

end

rule "LoanApplicationEvaluationRule_3"
    
	when
		la: LoanApplication(applicant.isCheckCreditOk == false)
	then
		la.setStatus("denied");

end